ALTER TABLE `user` MODIFY email VARCHAR(255) NOT NULL;
ALTER TABLE `user` MODIFY password VARCHAR(255) NOT NULL;
ALTER TABLE `user` ADD UNIQUE KEY uk_user_email (email);
CREATE INDEX idx_user_role ON `user` (role);

ALTER TABLE `user` ADD COLUMN created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6);
ALTER TABLE `user` ADD COLUMN updated_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6);
ALTER TABLE `user` ADD COLUMN created_by BIGINT NULL;
ALTER TABLE `user` ADD COLUMN updated_by BIGINT NULL;
